import 'dart:convert';
import 'package:fitman_app/services/api_service.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../models/building/building.model.dart';
import '../../providers/room/building_provider.dart';

class BuildingCreateScreen extends ConsumerStatefulWidget {
  const BuildingCreateScreen({super.key});

  @override
  ConsumerState<BuildingCreateScreen> createState() =>
      _BuildingCreateScreenState();
}

class _BuildingCreateScreenState extends ConsumerState<BuildingCreateScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _addressController = TextEditingController();
  final _noteController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Создать здание'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(labelText: 'Название *'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Пожалуйста, введите название';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _addressController,
                decoration: const InputDecoration(labelText: 'Адрес *'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Пожалуйста, введите адрес';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _noteController,
                decoration: const InputDecoration(labelText: 'Заметка'),
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: _createBuilding,
                child: const Text('Сохранить'),
              ),
            ],
          ),
        ),
      ),
    );
  }

  void _createBuilding() async {
    if (_formKey.currentState!.validate()) {
      final newBuilding = Building(
        id: '', // ID is generated by backend
        name: _nameController.text,
        address: _addressController.text,
        note: _noteController.text,
      );

      try {
        await ApiService.createBuilding(newBuilding);
        ref.invalidate(allBuildingsProvider);
        if (mounted) {
          Navigator.of(context).pop();
        }
      } catch (e) {
        if (mounted) {
          String errorMessage = 'Ошибка при создании здания: $e';
          Color backgroundColor = Theme.of(context).colorScheme.error;

          // Attempt to parse the error message if it's a JSON response from the backend
          try {
            final errorBody = jsonDecode(e.toString().replaceFirst('Exception: ', ''));
            if (errorBody is Map && errorBody.containsKey('error')) {
              errorMessage = errorBody['error'] as String;
              if (errorMessage == 'Здание с таким названием уже существует') {
                backgroundColor = Colors.red;
              }
            }
          } catch (_) {
            // Not a JSON error, use default message
          }

          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(errorMessage),
              backgroundColor: backgroundColor,
            ),
          );
        }
      }
    }
  }
}
